// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  HomeSidebar: [
    {
      type: "category",
      label: "Home",
      items: ["Home/home_1", "Home/home_2"],
    },
  ],
  QuickStartSidebar: [
    {
      type: "category",
      label: "Quick Start",
      items: ["QuickStart/index"],
    },
  ],
  TechnicalDocsSidebar: [
    {
      type: "category",
      label: "Technical Documentation",
      items: [
        "TechnicalDocs/index",
        "TechnicalDocs/APP/index",
        "TechnicalDocs/FirmWare/index",
        "TechnicalDocs/HardWare/index",
        "TechnicalDocs/HardWare/nihao",
      ],
    },
  ],
  ChangelogBlogSidebar: [
    {
      type: "category",
      label: "Changelog & Blog",
      items: [
        "Changelog_Blog/index",
        "Changelog_Blog/Blog/index",
        "Changelog_Blog/Changelog/index",
      ],
    },
  ],
  AboutUsSidebar: [
    {
      type: "category",
      label: "About Us",
      items: ["AboutUs/index"],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
