// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  TechnicalDocsSidebar: [
    {
      type: "category",
      label: "快速上手",
      items: [
        "TechnicalDocs/FirmWare/quickstart/preparation",
        "TechnicalDocs/FirmWare/quickstart/build",
        "TechnicalDocs/FirmWare/quickstart/flash",
      ],
    },
    {
      type: "category",
      label: "SDK介绍",
      items: [
        "TechnicalDocs/FirmWare/SDK-intro/JL-docs",
        {
          type: "category",
          label: "Buddie 新增模块",
          items: [
            "TechnicalDocs/FirmWare/SDK-intro/buddie-extras/intro",
            "TechnicalDocs/FirmWare/SDK-intro/buddie-extras/vad",
          ],
        }
      ],
    },
  ],

  ChangelogBlogSidebar: [
    {
      type: "category",
      label: "Changelog & Blog",
      items: [
        "Changelog_Blog/index",
        "Changelog_Blog/Blog/index",
        "Changelog_Blog/Changelog/index",
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
